event_register_audit: "就诊信息已提交审核，审核通过后即可加入*doctor_name*医生管理组。"

register_pass: |
    *patient_name*，您好。这里是*hospital_name**doctor_name*医生针的随访平台。

    在这里，
    1、您可以得到关于疾病全面、正规的知识。
    2、我们会通过这个平台持续关注患者在家的病情变化，对于治疗中的各种问题针对指导。另外，根据患者不同的治疗方案，系统会定期发送提醒，患者按照提醒操作即可，遇到问题可随时跟我们联系解决。
    (操作方法：点击微信左下角的'小键盘图标'切换成菜单或对话模式直接给我们发消息)

register_pass_ADHD: |
    *patient_name*家长，您好。这里是*hospital_name**doctor_name*医生针对ADHD（俗称多动症）孩子的帮助平台。

    在这里，您可以得到关于ADHD最全面、正规的知识，以及治疗中的各种常见问题的解答，我们还会对孩子的治疗效果进行持续性的评估，让您及时掌握孩子的情况。

    您有任何关于ADHD和孩子病情的疑惑，都可以直接询问。(操作方法：点击微信左下角的"小键盘图标"切换成菜单模式做评估或对话模式直接给我们发消息)

register_pass_PF: |
    *patient_name*，您好。这里是*hospital_name**doctor_name*医生针对肺间质纤维化患者的随访平台。

    在这里，
    1、您可以得到关于疾病全面、正规的知识。
    2、我们会通过这个平台持续关注患者在家的病情变化，对于治疗中的各种问题针对指导。另外，根据患者不同的治疗方案，系统会定期发送提醒，患者按照提醒操作即可，遇到问题可随时跟我们联系解决。
    (操作方法：点击微信左下角的'小键盘图标'切换成菜单或对话模式直接给我们发消息)

register_pass_IDDCNS: |
    *patient_name*，您好。这里是*hospital_name**doctor_name*医生针对炎性脱髓鞘病患者的随访平台。

    在这里，
    1、您可以得到关于疾病全面、正规的知识。
    2、我们会通过这个平台持续关注患者在家的病情变化，对于治疗中的各种问题针对指导。另外，根据患者不同的治疗方案，系统会定期发送提醒，患者按照提醒操作即可，遇到问题可随时跟我们联系解决。
    (操作方法：点击微信左下角的'小键盘图标'切换成菜单或对话模式直接给我们发消息)

register_pass_ra: |
    *patient_name*，您好。这里是*hospital_name**doctor_name*医生针对类风湿关节炎患者的随访平台。

    在这里，
    1、您可以得到关于疾病全面、正规的知识。
    2、您可以预约复诊，点击【我要】【约复诊】，预约您方便的复诊日期。
    3、我们会通过这个平台持续关注患者在家的病情变化，对于治疗中的各种问题针对指导。另外，根据患者不同的治疗方案，系统会定期发送提醒，患者按照提醒操作即可，遇到问题可随时跟我们联系解决。
    (操作方法：点击微信左下角的'小键盘图标'切换成菜单或对话模式直接给我们发消息)

register_pass_MPN: |
    *patient_name*，您好。这里是*hospital_name**doctor_name*医生针对骨髓增殖性肿瘤的随访平台。

    在这里，
    1、您可以得到关于疾病全面、正规的知识。
    2、我们会通过这个平台持续关注患者在家的病情变化，对于治疗中的各种问题针对指导。另外，根据患者不同的治疗方案，系统会定期发送提醒，患者按照提醒操作即可，遇到问题可随时跟我们联系解决。
    (操作方法：点击微信左下角的'小键盘图标'切换成菜单或对话模式直接给我们发消息)

register_pass_al: |
    *patient_name*，您好。这里是*hospital_name**doctor_name*医生针对浆细胞淀粉样变性的随访平台。

    在这里，
    1、您可以得到关于疾病全面、正规的知识。
    2、我们会通过这个平台持续关注患者在家的病情变化，对于治疗中的各种问题针对指导。另外，根据患者不同的治疗方案，系统会定期发送提醒，患者按照提醒操作即可，遇到问题可随时跟我们联系解决。
    (操作方法：点击微信左下角的'小键盘图标'切换成菜单或对话模式直接给我们发消息)

register_pass_lc: |
    *patient_name*，您好。这里是*hospital_name**doctor_name*医生针对肺癌的随访平台。

    在这里，
    1、您可以得到关于疾病全面、正规的知识。
    2、我们会通过这个平台持续关注患者在家的病情变化，对于治疗中的各种问题针对指导。另外，根据患者不同的治疗方案，系统会定期发送提醒，患者按照提醒操作即可，遇到问题可随时跟我们联系解决。
    (操作方法：点击微信左下角的'小键盘图标'切换成菜单或对话模式直接给我们发消息)

register_pass_Sarcoidosis: |
    *patient_name*，您好。这里是*hospital_name**doctor_name*医生针对肺结节的随访平台。

    在这里，
    1、您可以得到关于疾病全面、正规的知识。
    2、我们会通过这个平台持续关注患者在家的病情变化，对于治疗中的各种问题针对指导。另外，根据患者不同的治疗方案，系统会定期发送提醒，患者按照提醒操作即可，遇到问题可随时跟我们联系解决。
    (操作方法：点击微信左下角的'小键盘图标'切换成菜单或对话模式直接给我们发消息)

register_deny: 您的报到审核未通过，目前此公众号仅对指定医院就诊过的患者提供服务，如已就诊请上传就诊凭证（如挂号单、病历本首页等），有疑问请联系我们。

about_intro: 方寸泉香（北京）科技有限公司是一家创新型的互联网医疗公司。公司致力于运用互联网技术，服务于医院、医生和患者，提供方便、高效的管理服务，更好的提升患者的就诊效率和治疗效果。

about_service:  |
    我们始终坚持患者至上，对每一个孩子的健康和幸福给予诚挚和独特的关怀。

    服务内容：

    1.  复诊预约（提醒、预约等）
    2.  自测自测（及时调整，提升疗效）
    3.  定期记录康复日记
    4.  专业的知识推送，更深入的了解疾病

about_contact: |
    方寸泉香（北京）科技有限公司
    Tel: (8610) 82038177
    E-mail: fuwu@fangcunyisheng.com

education_already_send: 今天的知识已经看过了。每天了解一点，是最有效、省力的学习方式。

education_nomore: 非常棒，您已看到最新更新，敬请期待下一期。

event_subscribe: |
    欢迎关注『方寸儿童管理服务平台』微信公众号。

    请点》<a href="http://*host*/patient/bindtouser?openid=*openid*">我要</a> 报到，完善报到信息，以便接受院外管理。

scan_subscribe: |
    欢迎关注『方寸儿童管理服务平台』—*doctor_name*医生微信服务号。

    请点》<a href="http://*host*/patient/bindtouser?openid=*openid*">我要</a> 报到，完善报到信息，以便接受*doctor_name*医生的院外管理。

appointment_audit_pass: 您的预约申请已经通过，请根据我们的通知及时就诊。

appointment_btn_click: 您的预约申请已提交，请耐心等待工作人员审核。

click_assess: |
    请选择评估量表类型：

    》<a href=\"http://*host*/web/scale/show?name=adhd_iv&openid=*openid*\">*1.SNAP-IV评估</a>

    》<a href=\"http://*host*/web/scale/show?name=medicine_parent&openid=*openid*\">*2.疗效评估</a>

    》<a href=\"http://*host*/web/scale/show?name=sideeffect&openid=*openid*\"> 3.副反应评估</a>

    》<a href=\"http://*host*/web/scale/show?name=conners&openid=*openid*\"> 4.Conners父母用量表</a>

    *为必填

after_upload: 上传成功，孩子的资料已更新，可选择菜单中“我的”，点击“资料”查看。

after_diary: 日记已提交，如有问题会有工作人员给您回复。

after_sideeffect: |
    副反应评估量表已提交，请密切关注不良反应变化，及时告知我们；
    我们仔细评估不良反应后，如需复诊，给您办理复诊加号手续；
    可以在“我的”--“评估”查看评估量表的历史记录。
    <a href=\"http://mp.weixin.qq.com/s?__biz=MzAxMTM0Mjk0Mw==&mid=205878649&idx=1&sn=94d972ef2b7fc8366784b5d30f33ec41#rd\">点我</a> 了解小儿多动症用药常见不良反应。

after_fill: |
    *scalename*量表已提交，如需调整，我们会在
    查阅后与您联系；可以在“我的”--“评估”查看评估量表的历史记录。

need_to_fill: 尚需完成的评估：

already_filled: |
    评估已全部完成，如需调整，我们会在查阅后与您联系；
    可以在“我的”--“评估”查看评估量表的历史记录
    请确认孩子是否有不良反应，如有，请完成以下评估
    <a href=\"http://*host*/web/scale/show?name=sideeffect&openid=*openid*\">副反应评估</a>

adhd_iv: |
    <a href=\"http://*host*/web/scale/show?name=adhd_iv&openid=*openid*\">SNAP-IV评估</a>

medicine_parent: |
    <a href=\"http://*host*/web/scale/show?name=medicine_parent&openid=*openid*\">疗效评估</a>
