local socket = require("socket")
local time = socket.gettime()
--print(time)
--time = math.ceil(time * 10000)
time = math.ceil(time * 1000)
--print(time)
--math.randomseed(tostring(time):reverse():sub(1, 6)) 
--rand = math.random(10, 99)
--return  tostring(time)..tostring(rand)
return  tostring(time)
