<?php

class WxTaskArticle
{

    public function getArticlesByPos ($wxuser, $pos = 0) {
        $articles = array();
        $openid = $wxuser->openid;
        $result = array(
            1 => array(
                1 => array(
                    "title" => "据说看过这篇文章后，90%家长都会和孩子谈心了",
                    "img" => "http://img.fangcunyisheng.com/static/img/sfbt/sfbt05.jpg",
                    "content" => "恭喜您21天睡前谈心计划迈出了第一步，今天的谈心感受如何？
    方寸课堂精心为您准备了一篇谈心指南，来指导家长更好的和孩子谈心沟通。",
                    "url" => "http://wx.fangcunyisheng.com/sfbt/one?lessonid=102040509&openid={$openid}"),
                2 => array(
                    "title" => "细数七零八零后父母和孩子沟通的大坑(一)",
                    "img" => "http://img.fangcunyisheng.com/static/img/sfbt/sfbt06.jpg",
                    "content" => "第一坑：不要回避孩子的感受，哪怕是挫折",
                    "url" => "http://wx.fangcunyisheng.com/sfbt/one?lessonid=102137825&openid={$openid}"),
                3 => array(
                    "title" => "细数七零八零后父母和孩子沟通的大坑(二)",
                    "img" => "http://img.fangcunyisheng.com/static/img/sfbt/sfbt07.jpg",
                    "content" => "第二坑：别让“责问和教诲”堵住孩子的口",
                    "url" => "http://wx.fangcunyisheng.com/sfbt/one?lessonid=102140531&openid={$openid}"),
                4 => array(
                    "title" => "细数七零八零后父母和孩子沟通的大坑(三)",
                    "img" => "http://img.fangcunyisheng.com/static/img/sfbt/sfbt08.jpeg",
                    "content" => "第三坑：没用孩子能接受的方式讲道理",
                    "url" => "http://wx.fangcunyisheng.com/sfbt/one?lessonid=102162295&openid={$openid}"),
                5 => array(
                    "title" => "一招解决睡前谈心的内容问题",
                    "img" => "http://img.fangcunyisheng.com/static/img/sfbt/sfbt09.jpg",
                    "content" => "适用于每一天的睡前谈心策略",
                    "url" => "http://wx.fangcunyisheng.com/sfbt/one?lessonid=102173672&openid={$openid}"),
                6 => array(
                    "title" => "细数七零八零后父母和孩子沟通的大坑(四)",
                    "img" => "http://img.fangcunyisheng.com/static/img/sfbt/sfbt10.jpg",
                    "content" => "不要让情绪发泄影响解决问题（上）",
                    "url" => "http://wx.fangcunyisheng.com/sfbt/one?lessonid=102208422&openid={$openid}"),
                7 => array(
                    "title" => "细数七零八零后父母和孩子沟通的大坑(五)",
                    "img" => "http://img.fangcunyisheng.com/static/img/sfbt/sfbt10.jpg",
                    "content" => "不要让情绪发泄影响解决问题（下）",
                    "url" => "http://wx.fangcunyisheng.com/sfbt/one?lessonid=102228798&openid={$openid}"),
                8 => array(
                    "title" => "不批评、不谴责的让孩子认识所犯的错误",
                    "img" => "http://img.fangcunyisheng.com/static/img/sfbt/sfbt11.jpg",
                    "content" => "『21天睡前谈心』行至第八天，随着家长和孩子的逐渐适应，每天睡前谈心的几分钟，都已成为生活的固定时段。",
                    "url" => "http://wx.fangcunyisheng.com/sfbt/one?lessonid=102256126&openid={$openid}"),
                9 => array(
                    "title" => "谴责并不会促进孩子认识错误（上)",
                    "img" => "http://img.fangcunyisheng.com/static/img/sfbt/sfbt12.jpg",
                    "content" => "面对孩子所犯的错误，家长总希望通过谴责，深刻孩子对错误的认识，满怀愧疚的弥补当前错误。",
                    "url" => "http://wx.fangcunyisheng.com/sfbt/one?lessonid=102286346&openid={$openid}"),
                10 => array(
                    "title" => "谴责并不会促进孩子认识错误（下)",
                    "img" => "http://img.fangcunyisheng.com/static/img/sfbt/sfbt12.jpg",
                    "content" => "同谴责一样，威胁和埋怨也不会帮助孩子认识和反思问题。",
                    "url" => "http://wx.fangcunyisheng.com/sfbt/one?lessonid=102286560&openid={$openid}"),
                11 => array(
                    "title" => "懂得规矩和惩罚的区别",
                    "img" => "http://img.fangcunyisheng.com/static/img/sfbt/sfbt13.jpeg",
                    "content" => "很多人以为“做规矩”和“惩罚”是一回事，其实大不相同。",
                    "url" => "http://wx.fangcunyisheng.com/sfbt/one?lessonid=102346342&openid={$openid}"),
                12 => array(
                    "title" => "对孩子，别太快说“不”！",
                    "img" => "http://img.fangcunyisheng.com/static/img/sfbt/sfbt14.jpeg",
                    "content" => "在某些场合上，需要对孩子们说“不”，从而阻止他们进行某些危险的或者不恰当的行为。但有时候，家长似乎太轻易说“不”，而忘了考虑是否有可能说“可以”。",
                    "url" => "http://wx.fangcunyisheng.com/sfbt/one?lessonid=102369806&openid={$openid}"),
                13 => array(
                    "title" => "对于孩子的正性行为给予更多的关注",
                    "img" => "http://img.fangcunyisheng.com/static/img/sfbt/sfbt15.jpeg",
                    "content" => "家长经常疲于纠正孩子的不良行为，而常常忽视了孩子的良好行为。",
                    "url" => "http://wx.fangcunyisheng.com/sfbt/one?lessonid=102394948&openid={$openid}"),
                14 => array(
                    "title" => "提前为可能到来的问题做好准备",
                    "img" => "http://img.fangcunyisheng.com/static/img/sfbt/sfbt16.jpg",
                    "content" => "家长们通常都会在问题发生的时候，疲于救场，而并非提前预期可能出现怎样的问题，以及提前做好对可能出现的问题的应对方法。",
                    "url" => "http://wx.fangcunyisheng.com/sfbt/one?lessonid=102418488&openid={$openid}"),
                15 => array(
                    "title" => "还在长篇大论教育孩子的家长，请歇歇吧！",
                    "img" => "http://img.fangcunyisheng.com/static/img/sfbt/sfbt17.jpg",
                    "content" => "孩子犯错以后，很多家长总希望孩子能通过这次犯错有更多的收获和成长。于是采取了将道理和自己的经验掰开揉碎，并不断地重复和强调的方式，期待获得孩子思想的更多认同和吸收。",
                    "url" => "http://wx.fangcunyisheng.com/sfbt/one?lessonid=102452358&openid={$openid}"),
                16 => array(
                    "title" => "啥呀？对孩子“发火”还讲究姿势哩？（上）",
                    "img" => "http://img.fangcunyisheng.com/static/img/sfbt/sfbt18.jpg",
                    "content" => "每天和孩子相处，对于家长而言，想不发火真的很难！往往刚刚表扬完孩子，心里暖暖暖的，不出一会，就会惹出大的麻烦来，让家长的思维永远跟不上孩子的节奏。",
                    "url" => "http://wx.fangcunyisheng.com/sfbt/one?lessonid=102474944&openid={$openid}"),
                17 => array(
                    "title" => "啥呀？对孩子“发火”还讲究姿势哩？（下）",
                    "img" => "http://img.fangcunyisheng.com/static/img/sfbt/sfbt19.jpg",
                    "content" => "（接上篇）往往家长在发火的时刻更关注于情绪的发泄，而不是状况的处理，这正是问题所在。",
                    "url" => "http://wx.fangcunyisheng.com/sfbt/one?lessonid=102489858&openid={$openid}"),
                18 => array(
                    "title" => "用口头命令无法解决的问题？试试便条",
                    "img" => "http://img.fangcunyisheng.com/static/img/sfbt/sfbt20.jpeg",
                    "content" => "很多家长反馈：家长的指令孩子已经答应了，但是最终的结果依然是未执行，这时该怎么办？试试把指令写出来，用便条来提醒孩子。",
                    "url" => "http://wx.fangcunyisheng.com/sfbt/one?lessonid=102503832&openid={$openid}"),
                19 => array(
                    "title" => "老师告状怎么办？",
                    "img" => "http://img.fangcunyisheng.com/static/img/sfbt/sfbt21.jpg",
                    "content" => "来自一位家长的分享",
                    "url" => "http://wx.fangcunyisheng.com/sfbt/one?lessonid=102522072&openid={$openid}"),
                20 => array(
                    "title" => "比惩罚更有效的教育方式，都在这了(上)",
                    "img" => "http://img.fangcunyisheng.com/static/img/sfbt/sfbt22.jpg",
                    "content" => "孩子犯错以后，很多家长会希望通过惩罚使孩子记住这次错误。然而，事实却往往和家长的预期背道而驰。相同的错误一而再的出现，惩罚并没有达到预期的目的。",
                    "url" => "http://wx.fangcunyisheng.com/sfbt/one?lessonid=102545860&openid={$openid}"),
                21 => array(
                    "title" => "比惩罚更有效的教育方式，都在这了(下)",
                    "img" => "http://img.fangcunyisheng.com/static/img/sfbt/sfbt22.jpg",
                    "content" => "（接上篇）用一个完整的情景来明确代替惩罚的处理方式。",
                    "url" => "http://wx.fangcunyisheng.com/sfbt/one?lessonid=102577010&openid={$openid}")),
            2 => array(
                1 => array(
                    "title" => "追踪游戏 NO.1",
                    "img" => "http://img.fangcunyisheng.com/static/img/sfbt/line.jpg",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=417385236&idx=1&sn=57ccf687ff8930b7bfea140c4b6e9ed5"),
                2 => array(
                    "title" => "追踪游戏 NO.2",
                    "img" => "http://img.fangcunyisheng.com/static/img/sfbt/line.jpg",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=417389932&idx=1&sn=dac886773d53fb1a553163f8df095ed7"),
                3 => array(
                    "title" => "追踪游戏 NO.3",
                    "img" => "http://img.fangcunyisheng.com/static/img/sfbt/line.jpg",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=417394798&idx=1&sn=fc42288b76aa510ba2c15dce1ee54769"),
                4 => array(
                    "title" => "追踪游戏 NO.4",
                    "img" => "http://img.fangcunyisheng.com/static/img/sfbt/line.jpg",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=417394896&idx=1&sn=64b9f505f1628c64f54a1e09550c2abb"),
                5 => array(
                    "title" => "目视迷宫 NO.1",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK03eGQXRLAiaAfJOHR90iaWceIrIxxMz8Z6EZf5xPsa0WoJpPs6aHzQbf2OGwgyRK1ZCWoFgqaxyMGQ/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=417476993&idx=1&sn=0981272955314f387dc2101169469229"),
                6 => array(
                    "title" => "目视迷宫 NO.2",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK2XC7bZ5FDeHDfln2nXyfCfiaMa2LJwgr1gCguqPwibGe52sq35U0CO9m0TBT1c1kjdiaH7RxSLz4WjQ/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=417542234&idx=1&sn=ef622831918dd6d1b488f7912b33d774"),
                7 => array(
                    "title" => "目视迷宫 NO.3",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK2e6Vvznz5tGeCSdyFgliaxhFFpff0bYx8icfNKr0XcXrFCaf6l2T1iasknusJibpO5X9LkmibSxKKVyIg/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=417612610&idx=1&sn=286e52ca19306b3eac6f49f9c0c95502"),
                8 => array(
                    "title" => "目视迷宫 NO.4",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK2e6Vvznz5tGeCSdyFgliaxhUO2pohM0zZZBJmtgMtes2nkL6lazeUqzkbClV8ZVXVjwvicloWlFTsw/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=417614585&idx=1&sn=af90da58f4a2a6521b90e29a63b3360a"),
                9 => array(
                    "title" => "一笔一画NO.1",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK1hMAI7qt6M7UmqA0Iw9Nb0la24y65TLBdc8IMHGZWCnktBLkPjuoW34Lvb3aXbBiazgQlnLPyzWdA/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=417751728&idx=1&sn=249e9bebe525936d1d7d7b672ed28f4a"),
                10 => array(
                    "title" => "一笔一画NO.2",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK1hMAI7qt6M7UmqA0Iw9Nb0YicQiaGzfA4dQAr3icrQblP1sO3qxRC4VC5yx9TU0icSyldbCsvCWwqlhQ/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=417752919&idx=1&sn=2609f266b96836583d59ec0011d118cc"),
                11 => array(
                    "title" => "一笔一画NO.3",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK1hMAI7qt6M7UmqA0Iw9Nb02vyXRaaMt6AjphtRXmKqpib3IodMicHpr4dysC93uk7bRm55VxETJb3Q/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=417753214&idx=1&sn=9f2772707a3a165e3694ec76979cf28a"),
                12 => array(
                    "title" => "一笔一画NO.4",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK1hMAI7qt6M7UmqA0Iw9Nb024IWduRYSiaVqQQSXeeTIVPIMYGiaaL9rhdZy8g0PqmYUoh4icK1PtHrw/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=417754603&idx=1&sn=0672de32ca68aedbdd84c10a1ec732ac"),
                13 => array(
                    "title" => "找不同NO.1",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK0S2onvIrk7W4YRZ1It5YY8k8drWiaqBPtOubMC3nkY7mFpBzk6t9CzL8MicdebAnUqCdMia8IrZUVEg/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=417966066&idx=1&sn=beb677a6654833d8a6395b19e5846b60"),
                14 => array(
                    "title" => "找不同NO.2",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK0S2onvIrk7W4YRZ1It5YY838ibIqdjVu5uuLsSSCibTOTibhu8qEjFBUywdCxoykUiaycpvJSU1HRppA/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=417967041&idx=1&sn=37412cc7615ce4983ff364f41f0b174e"),
                15 => array(
                    "title" => "找不同NO.3",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK0S2onvIrk7W4YRZ1It5YY8PcqJWClVaO73yvLFqRLNvH6VrYDsZGuxHTib2yice7KKYR33IT9ndarQ/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=417967819&idx=1&sn=9543a742d046e3d7ef4df1e6297a5628"),
                16 => array(
                    "title" => "找不同NO.4",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK0S2onvIrk7W4YRZ1It5YY84SRe089wFWuzOLlOxmEkvDC08bBrfnNyhSq1FYS2O9ibxCH4tLBzaPQ/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=417968311&idx=1&sn=874db6bb30d480c070a6c7e26517e90d"),
                17 => array(
                    "title" => "生活场景游戏NO.1",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK1BbD88sxO8biax6cxTO5liaQ7j99C9cjtQneLGhkPH0sV8yUsI11uzgxlcl8MlSwxRic6k0T0XDRlZQ/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=418754183&idx=1&sn=d91a386fd5821b7e88f637fb1b431e79"),
                18 => array(
                    "title" => "生活场景游戏NO.2",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK1BbD88sxO8biax6cxTO5liaQptuHI0BnElD8bvict1NQcu027QE9OMaUauWkrx0w9Bgzpc9wpicicRrZw/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=418757578&idx=1&sn=bd4889a067c04ea65d48767fdbf8c70e"),
                19 => array(
                    "title" => "生活场景游戏NO.3",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK1BbD88sxO8biax6cxTO5liaQSvicVTcKZqMde5AMWBG8lSmC5OSf3Z2iaaaM8Kz8aBZMQYicMfHlkwMNQ/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=418758165&idx=1&sn=15fc24101a0e4f5e375bc351862596c2"),
                20 => array(
                    "title" => "生活场景游戏NO.4",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK1BbD88sxO8biax6cxTO5liaQubpv779FIPoGshfCFiav8L9CR0VL5RIbrCr12ibqFnIpmLJmiawPRXX7g/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=418758925&idx=1&sn=e605120d1b4dd1ddd8aff63d9aff91ce"),
                21 => array(
                    "title" => "21天睡前谈心计划--游戏专题收尾",
                    "img" => "http://mmbiz.qlogo.cn/mmbiz/6yvoELN4gK1BbD88sxO8biax6cxTO5liaQ2uIbeEL0bqwYlz60cYkSkPnDCu2z8PHIYzZj2Acu9icC2uguCFjyMXA/0?wx_fmt=jpeg",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=418762054&idx=1&sn=e0019439ffaf55203575a4ce052d13aa")),
            3 => array(
                1 => array(
                    "title" => "改变自己",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK2msVF8lrxqbrjX6DYK2Lia4CQQjlMibGg0n5IvZH5a8xhNg7gby7wtWticsKucvJyYuCUYeNw9NibqFA/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=518763497&idx=1&sn=3ba678c2caa81bedd4bf4c1ab2c987a6"),
                2 => array(
                    "title" => "学会用心倾听",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK3PSZF297DQEibXCXqJ9yUWl8hdtAwoUfSlRXuYcI0A9P6ej1RPSNaGg2jhUveDkeH9LerPibYy7vHA/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=518763511&idx=1&sn=4415f94355ca06219cde1de2427efcf4"),
                3 => array(
                    "title" => "写便条",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK3PSZF297DQEibXCXqJ9yUWlrV16Kaz532LrZVzlf78BcKGYhEol5d9sbuII1ibBUKvc1HWHgNo7jKA/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=518763514&idx=1&sn=b3730e4b26e3a226919f945ff687af17"),
                4 => array(
                    "title" => "放手让孩子自己选择",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK3PSZF297DQEibXCXqJ9yUWltuY271y7WHAxRhsI7h9uCLb1TQZ2b3RAcFwkZXsKqibPbFoJC7ML4ww/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=518763517&idx=1&sn=b05a5b7f411aa074cf11f5e7fa79fb52"),
                5 => array(
                    "title" => "学会用描述性赞赏",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK1kZkElfTGVxuzTxy8Wx6J20BwdjMebf1W3PsVOj7ZcJVVNl0IIZK9PhXZHWR4VibGvtoAOK2G8FkQ/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=518763520&idx=1&sn=852c2ee7ab58c18764ad3bd96799bca6"),
                6 => array(
                    "title" => "创造机会让孩子另眼看自己",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK2G63g1rmmuFchgcqo98K7Pqu4Ub2rmfauuA4MHICwSpLeMJZNVhwl5LmjD5my8iceUAJX65GAPGKQ/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=518763521&idx=1&sn=3c20a5736615e4b631801c6241d5e186"),
                7 => array(
                    "title" => "让孩子听到你的表扬",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK1L26QXPUp4p2oTnlRH7koDv0gOZG7vE4NmfUcjWMep0xOTic7M7cPhic0XBrib8Ll4ibgDEHrmkicVVBA/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=518763524&idx=1&sn=20f8a774960428d8eb03dfd3c921f651"),
                8 => array(
                    "title" => "以身作则陪孩子一起进行睡前阅读",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK1L26QXPUp4p2oTnlRH7koD8bDAHOe8lItGkwkAH5rWEQTxnervh0Uxnhtk5oCEHjvs5JJvsn1hEg/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=518763527&idx=1&sn=68821edb820f9627b65f2688e7d28994"),
                9 => array(
                    "title" => "问问孩子心目中的父母",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK3KibKgpS1DHTrnOiaqLO3ASoHBv5c5L5cHca3uuWmzibH9ZZMpc4fT1godRPJveS9OibbeF5B1oBZaUg/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=518763530&idx=1&sn=0af37ec28fffedbb39f4ea8e289bb2f6"),
                10 => array(
                    "title" => "告诉孩子你的期望",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK3KibKgpS1DHTrnOiaqLO3ASoAVJibHkFy4fRibZmq1T9gAtznuM0tRCrQ37xxHEzzTL8r8c48eAw02dg/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=518763533&idx=1&sn=179120564350218a1aac476ceadf15ab"),
                11 => array(
                    "title" => "写篇孩子的成长日记很有必要",
                    "img" => "http://mmsns.qpic.cn/mmsns/6yvoELN4gK3mj2harp2SzFY6NnZBaCpmT8ictZ8vD2smSTadrT12cWw/0?wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=518763538&idx=1&sn=6184083b0c9844c5ca5b847c221ecb47"),
                12 => array(
                    "title" => "用爱的声音感动孩子",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK0wxnDhPf2fYTW4Ucere5bY7455NoxWMB3PQFredWXfvM7ZeqqqaictSYFiacX1dce7bpwoMibJOyQeg/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=518763542&idx=1&sn=d9b3489ab3d323b70eb54ec2c0912df8"),
                13 => array(
                    "title" => "遇见20年后的父母",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK27VH5sIQ22PWfpFGRJygqfIgNhdkE6WO5HibSyibeKbJRnz13icmt7mnch52dGfOLOF5EbAht6yEDxA/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=518763548&idx=1&sn=ab91a980358dceb4b7688650e13377ad"),
                14 => array(
                    "title" => "教孩子做一顿晚餐",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK2dz94cEm6Qt6A0Ey2BzyiakvwPsf5UZMmfTjr6LzWwHdVjKet1OhV52tlibTHVhN8tpzFwvQeBFktw/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=518763551&idx=1&sn=236945c1416a85b068b32fd8b4eb28bd"),
                15 => array(
                    "title" => "讲讲孩子小时候的故事",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK1AroXlKAicibZfySaV9ViaWQ2fibDSMicmliaKaIDmxpMcNS1RZmWCV1PbzsIbQ7xdlffOCOAORNMz4qCw/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=518763554&idx=1&sn=af1e3a769f90bf198b1a4409459190e7"),
                16 => array(
                    "title" => "让孩子学会去爱",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK1AroXlKAicibZfySaV9ViaWQ2d7tB6lvsHIjvBicRLxQB8w6IqAvVjniaKNYcoSgXf3qg0ibcoULNLEVDg/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=518763560&idx=1&sn=920cbb93cffe06163fad5f2e3bcbbf5e"),
                17 => array(
                    "title" => "写篇孩子的成长日记很有必要",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK1AroXlKAicibZfySaV9ViaWQ2k5zBqiayDw1eSr6rzU4aFugkxqwhD4icLGTy9mPw77NU1xMGkDGGYAgQ/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=518763557&idx=1&sn=7294ef442f3a5a081435f83ab12708aa"),
                18 => array(
                    "title" => "让孩子听话的秘密——和善而坚定",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoeln4gk3sx4suztm9a2xlxaicheafsat7hxmelhdibfo7rfz7hzlxvxmsxj2ywtsrm31systlucb1jibpbian1a/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=518763563&idx=1&sn=664fa09b0e3782c8513f58a4ad70fc56"),
                19 => array(
                    "title" => "四步教你赢得孩子的合作",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK3ENjuCd9vDK818fG2HYn6eDciblXjtRazVwFmT8RC4SGpBNjibhGFd0fyZGbk4SWVzFnxDh7QT766A/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=518763568&idx=1&sn=9fd5bcbc42f1be7a38cc19ae3765846e"),
                20 => array(
                    "title" => "学会“启发式问题”很有必要",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK3ENjuCd9vDK818fG2HYn6eEyiaGjlSZ3RdibXBgic4uGJELETR9WHYpqtB14uBYZUicrD9DuZNwPkACw/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=518763571&idx=1&sn=06e40e235123de1ccf76eba50314eb14"),
                21 => array(
                    "title" => "陪伴是最长情的告白",
                    "img" => "http://mmbiz.qpic.cn/mmbiz/6yvoELN4gK1BbD88sxO8biax6cxTO5liaQ2uIbeEL0bqwYlz60cYkSkPnDCu2z8PHIYzZj2Acu9icC2uguCFjyMXA/640?wx_fmt=jpeg&tp=webp&wxfrom=5&wx_lazy=1",
                    "content" => "",
                    "url" => "http://mp.weixin.qq.com/s?__biz=MzI3NjA3MjU4NA==&mid=518763572&idx=1&sn=5f01b7c67a30f480f727c6ab03e3b793")));

        if (! $pos) {
            return $result;
        }

        $cnt = $wxuser->getWxTaskCnt("listen");
        $item = $result[$cnt][$pos];
        if (is_array($item)) {
            $articles[] = new SimpleWxMsg($item['title'], $item['img'], $item['content'], $item['url']);
        }
        return $articles;
    }
}
