#!/usr/bin/env ruby

require 'rest-client'

url = 'wx.fcfc.com:3000/wxiddcns/gate?debugkey=fcqx'
xml = %Q{
<xml>
<ToUserName><![CDATA[gh_b185f11b36e8]]></ToUserName>
<FromUserName><![CDATA[12312312312312a3123]]></FromUserName>
<CreateTime>123456789</CreateTime>
<MsgType><![CDATA[event]]></MsgType>
<Event><![CDATA[subscribe]]></Event>
<EventKey><![CDATA[qrscene_123123]]></EventKey>
</xml>
}

=begin
<Ticket><![CDATA[TICKET]]></Ticket>
xml = %Q{
<xml>
<ToUserName><![CDATA[gh_97b67f241dd5]]></ToUserName>
<FromUserName><![CDATA[oiOZEw5qvIuPWua4LcYuLgZjLiGU]]></FromUserName>
<CreateTime>1448432954</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[1448432954]]></Content>
<MsgId><![CDATA[6220972168279843216]]></MsgId>
</xml>
}
=end

result = RestClient.post url, xml, content_type: "xml", accept: "xml"

puts result
